#! /bin/bash

##################################
# Easy Coding 2 config File      #
##################################

# load parent
loadCfg ".default_kk"

# customize
CFG_DIR_PROJECT="alto45_orange"
CFG_NAME_PROJECT="alto45_orange"
CFG_DIR_OUT="out/target/product/$CFG_NAME_PROJECT"
CFG_ENV_CONFIG="choosecombo 1 $CFG_NAME_PROJECT userdebug 2 2"

CFG_BRANCH="kk8916_orange"
