#! /bin/bash

##################################
# Easy Coding 2 config File      #
##################################

# load parent
loadCfg ".default_jb22_cdr"

# customize
CFG_DIR_PROJECT="bigs"
CFG_NAME_PROJECT="ningbo"
CFG_DIR_OUT="out/target/product/ningbo"
CFG_ENV_CONFIG="choosecombo 1 ningbo eng 2 2"

CFG_BRANCH="bigs_dev"
