#! /bin/bash

##################################
# Easy Coding 2 config File      #
##################################

# load parent
loadCfg ".default_8926"

# customize
CFG_DIR_PROJECT="eos4g_cmcc"
CFG_NAME_PROJECT="eos4g_cmcc"
CFG_DIR_OUT="out/target/product/$CFG_NAME_PROJECT"
CFG_ENV_CONFIG="choosecombo 1 $CFG_NAME_PROJECT userdebug 2 2"

CFG_BRANCH="ver/eos4g_cmcc/eos4g_cmcc_jb32_qrd_v2C1E_0"
