#! /bin/bash

##################################
# Easy Coding 2 config File      #
##################################

# load parent
loadCfg ".default_8926"

# customize
#CFG_DIR_PROJECT="rio6"
CFG_NAME_PROJECT="rio6"
CFG_DIR_OUT="out/target/product/$CFG_NAME_PROJECT"
CFG_ENV_CONFIG="choosecombo 1 $CFG_NAME_PROJECT userdebug 2 2"

CFG_BRANCH="jb32_cdr"
