#! /bin/bash

##################################
# Easy Coding 2 config File      #
##################################

# load parent
loadCfg ".default_l8916"

# customize
CFG_DIR_PROJECT="simba"
CFG_NAME_PROJECT="simba6x"
CFG_DIR_OUT="out/target/product/$CFG_NAME_PROJECT"
CFG_ENV_CONFIG="choosecombo 1 $CFG_NAME_PROJECT userdebug 2 2"

CFG_BRANCH="n8996"

CFG_CLONE_BRANCH_TYPE="m"
