#! /bin/bash

##################################
# Easy Coding 2 config File      #
##################################

# load parent
loadCfg ".default_l8916"

# customize
CFG_DIR_PROJECT="m01_c2"
CFG_NAME_PROJECT="c2"
CFG_DIR_OUT="out/target/product/$CFG_NAME_PROJECT"
CFG_ENV_CONFIG="choosecombo 1 $CFG_NAME_PROJECT userdebug 2 2 2"

CFG_BRANCH="n8996_t2m_m01_c2"
