#! /bin/bash

##################################
# Easy Coding 2 config File      #
##################################

# load parent
loadCfg ".default_bb"

# customize
CFG_DIR_PROJECT="mercury"
CFG_NAME_PROJECT="bbry_qc8953"
CFG_DIR_OUT="out/target/product/$CFG_NAME_PROJECT"
#CFG_ENV_CONFIG="choosecombo 1 $CFG_NAME_PROJECT userdebug 2 2"
CFG_ENV_CONFIG="lunch bbry_qc8953_sfi-userdebug"

CFG_BRANCH="bb/develop/tcl/jdm/app"
