#! /bin/bash

##################################
# Easy Coding 2 config File      #
##################################

# load parent
loadCfg ".default_8926"

# customize
CFG_DIR_PROJECT="pe_dev"
CFG_NAME_PROJECT="miata"
CFG_DIR_OUT="out/target/product/$CFG_NAME_PROJECT"
CFG_ENV_CONFIG="choosecombo 1 $CFG_NAME_PROJECT user 2 2"

CFG_BRANCH="pe_dev"
