#! /bin/bash

###############################
# functions begin             #
function remount() {
    # $1: partition name (i.e. /system)
    adb shell mount | while read LINE; do
        MATCH=`expr "$LINE" : ".*$1"`
        if [ "$MATCH" -ne "0" ]; then
            LINE="${LINE%?$1*}"
            print i "Remounting $1 ..."
            adb shell mount -o rw,remount -t yaffs2 $LINE
            print i "Done"
            break
        fi
    done
    
    # clean up
    unset MATCH
    unset LINE
}

function adb_push() {
    # $1: name (name displayed to end user)
    # $2: source
    # $3: dest
    print i "Sending $1 ..."
    if [ -e $2 ]; then
        # create folder on device
        adb shell mkdir -p $3

        # push file
        adb push "$2" "$3"
    else
        print w "File not exists. Ignore it"
    fi
    print i "Done"
}
# functions end               #
###############################

# get root for userdebug version
adb root
sleep 2

# switch out dir
import "cmd/switch-out"

PROJECT_OUT="$CFG_DIR_BASE/$CFG_DIR_PROJECT/$CFG_DIR_OUT"
PROJECT_BRANCH="$CFG_BRANCH"

if [ -z "$1" ]; then
    print e "Invaild parameter"
    print w "Please input which app you would like to push"
    exit 0
elif [ "$1" == "-l" ]; then
    ls "$PROJECT_OUT""/system/app/"
    exit 0
fi

AppName="$1"
ApkSrc="$PROJECT_OUT/system/app/$AppName/$AppName.apk"
ApkDest="/system/app/$AppName"
OdexSrc="$PROJECT_OUT/system/app/$AppName/oat/arm64/$AppName.odex"
OdexDest="/system/app/$AppName/oat/arm64"
PrivAppSrc="$PROJECT_OUT/system/priv-app/$AppName/$AppName.apk"
PrivAppDest="/system/priv-app/$AppName"
PrivOdexSrc="$PROJECT_OUT/system/priv-app/$AppName/oat/arm64/$AppName.odex"
PrivOdexDest="/system/priv-app/$AppName/oat/arm64"
FrameworkJarSrc="$PROJECT_OUT/system/framework/$AppName.jar"
FrameworkJarDest="/system/framework"
FrameworkApkSrc="$PROJECT_OUT/system/framework/$AppName.apk"
FrameworkApkDest="/system/framework"
FrameworkOdexSrc="$PROJECT_OUT/system/framework/oat/arm64/$AppName.odex"
FrameworkOdexDest="/system/framework/oat/arm64/"
VendorApkSrc="$PROJECT_OUT/system/vendor/app/$AppName/$AppName.apk"
VendorApkDest="/system/vendor/app/$AppName"
VendorOdexSrc="$PROJECT_OUT/system/vendor/app/$AppName/oat/arm64/$AppName.odex"
VendorOdexDest="/system/vendor/app/$AppName/oat/arm64"


# do remount for cdr
print i "Do remount before push"
remount "/system"
remount "/custpack"

print i "Begin push"
adb_push "[/system/app] APK" $ApkSrc $ApkDest
adb_push "[/system/app] ODEX" $OdexSrc $OdexDest
adb_push "[/system/priv-app] APK" $PrivAppSrc $PrivAppDest
adb_push "[/system/priv-app] ODEX" $PrivOdexSrc $PrivOdexDest
adb_push "[/system/framework] JAR" $FrameworkJarSrc $FrameworkJarDest
adb_push "[/system/framework] APK" $FrameworkApkSrc $FrameworkApkDest
adb_push "[/system/framework] ODEX" $FrameworkOdexSrc $FrameworkOdexDest
adb_push "[/system/vendor/app] APK" $VendorApkSrc $VendorApkDest
adb_push "[/system/vendor/app] ODEX" $VendorOdexSrc $VendorOdexDest
print i "End push"

# clean up
unset PROJECT_OUT
unset PROJECT_BRANCH
unset AppName
unset ApkSrc
unset ApkDest
unset OdexSrc
unset OdexDest
unset PrivAppSrc
unset PrivAppDest
unset PrivOdexSrc
unset PrivOdexDest
unset FrameworkJarSrc
unset FrameworkJarDest
unset FrameworkApkSrc
unset FrameworkApkDest
unset FrameworkOdexSrc
unset FrameworkOdexDest
