#! /bin/bash

TARGET_REAL_OUT_DIR="$CFG_DIR_BASE/$CFG_DIR_PROJECT/outs/$CFG_NAME_PROJECT"
OUT_DIR="$CFG_DIR_BASE/$CFG_DIR_PROJECT/out"
CURRENT_REAL_OUT_DIR=$(readlink -f "$OUT_DIR")

print i "Current out: $CURRENT_REAL_OUT_DIR"
print i "Target out: $TARGET_REAL_OUT_DIR"

if [ "$TARGET_REAL_OUT_DIR" != "$CURRENT_REAL_OUT_DIR" ]; then
    print i "Should should update out link to target"
    if [ -e $OUT_DIR ]; then
        rm -rf $OUT_DIR
    fi

    mkdir -p "$TARGET_REAL_OUT_DIR"

    ln -s "$TARGET_REAL_OUT_DIR" "$OUT_DIR"
else
    print i "Unnecessary to update out link"
fi

unset REAL_OUT_DIR
unset OUT_DIR
unset CURRENT_REAL_OUT_DIR
